name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build Docker containers
      run: |
        docker-compose build

    - name: Start Docker containers
      run: |
        docker-compose up -d

    - name: Test Kong API
      run: |
        curl -i http://localhost:8001/
        curl -i http://localhost:8001/services

    - name: Run tests
      run: |
        # Ajoute ici les tests pour ton application

    - name: Deploy Application
      if: github.ref == 'refs/heads/main'
      run: |
        docker-compose down
        docker-compose up -d
